player = {
    "Name": 'Player',
    "HP": 1,
    "Max_HP": 100,
    "Energy": 0,
    "Max_Energy": 10,
    "Level": 1,
    "EXP": 0,
    "Need_EXP": 100,
    "ATK": 10,
    "Heal": 10,
    "SPoint": 90,
    "SPoint_Add": 10,
    "SCost": 10,
    "IMagic": 0,
    "INecro": 0,
    "IFArrow": 0,
    "IMHeal": 0,
    "Inventory": { },
    "Last_Enemy": 'Goblin',
    "X": 0,
    "Y": 0,
    "Location_x": 0,
    "Location_y": 0,
    "Old_Location_x": 0,
    "Old_Location_y": 0,
}
